リザルト画面
masayukid/PocketFooskicker pull request #18
Opened 2024-12-30 08:38 UTC by Kenshin0011

2024-12-30 19:59 UTC, Kenshin0011 commented on Assets/Plugins/ParticleEffectForUGUI-main.meta
CanvasでScreen Space OverlayでParticleを表示できるようにプラグイン入れてみました
https://www.youtube.com/watch?v=_JM0g9jzOk0

2024-12-30 19:59 UTC, Kenshin0011 commented on Assets/Scripts/ResultManager.cs
> +        Vector2 rightPosition = new Vector2(canvasWidth / 8, canvasHeight / 8);
なんかプラグインの影響か、左右対称の数値にならなかったです

2025-01-01 13:54 UTC, masayukid commented on Assets/Scripts/GameController.cs
> +        if (goalPlayer.IsSelf && _selfPlayer.Score.IsWinningScore())
ScoreにIsWinningScore()を実装して公開するより、Player側にIsWinningScore()を定義してあげる方がよさそう。
勝利スコアはScoreBoardクラスのランプ数から取ってくるとマジックナンバーを減らせる。

2025-01-01 13:59 UTC, masayukid commented on Assets/Scripts/GameController.cs
> +    }
この処理なら、引数はPlayerで受け取らず、boolでIsSelfを受け取るので十分かもしれない。
そうすると呼び出し側の分岐を減らせる。多分こんな感じになる。

if (_goalPlayer.IsWinningScore()) {
    EndGame(_goalPlayer.IsSelf);
    return;
}

2025-01-01 14:03 UTC, masayukid commented on Assets/Scripts/ResultManager.cs
> +    [SerializeField] private Canvas canvas;
一応命名ルールを統一させておきたいから、privateなフィールドには頭にアンダーバーを付けておこう。

```suggestion
    [SerializeField] private TextMeshProUGUI _scoreText;
    [SerializeField] private TextMeshProUGUI _resultMessage;
    [SerializeField] private GameObject _victoryParticlePrefab;
    [SerializeField] private Canvas _canvas;
```

2025-01-01 14:17 UTC, masayukid commented on Assets/Scripts/ResultManager.cs
> +        Vector2 rightPosition = new Vector2(canvasWidth / 8, canvasHeight / 8);
環境（解像度）によって表示位置がズレているので、値の取得方法を見直す必要がありそう。
スクリーン座標とワールド座標の変換周りの問題な気がする。

こっちの環境の問題の可能性もあるから、Gameビューの解像度を変えても正しく表示されるか確かめてみてほしい。

2025-01-01 14:20 UTC, masayukid commented on Assets/Scripts/ResultManager.cs
> +        Destroy(particleEffect, 5.0f);
ParticleSystemにStopActionという項目があって、Destroyに設定するとこれ書かなくてもやってくれる。

2025-01-01 14:22 UTC, masayukid commented on Assets/Scripts/ResultManager.cs
> +        }
ParticleSystemのPlayOnAwakeにチェックマークが入っていたので、多分これ書かなくても生成された瞬間に再生される。

2025-01-02 06:52 UTC, masayukid requested changes
クラッカーの演出、すごく良いと思いました！
ただ、環境によっては本来右側に生成されるであろうオブジェクトが画面中央に表示されていたりしていました。
表示位置が解像度によってズレないように修正をお願いします。

その他、Unityの機能や設計に関する改善案をいくつか提案しているので、ご確認をお願いします。

2025-01-03 04:37 UTC, Kenshin0011 commented on Assets/Scripts/GameController.cs
> +        if (goalPlayer.IsSelf && _selfPlayer.Score.IsWinningScore())
Playerに勝利者かどうかの責務を持たせて、ScoreはIsWinningScoreにすることで、勝利条件の変更に強くしました

2025-01-03 05:00 UTC, Kenshin0011 commented on Assets/Scripts/ResultManager.cs
> +    [SerializeField] private Canvas canvas;
すんません、めっちゃ忘れます😅

2025-01-03 05:09 UTC, Kenshin0011 commented on Assets/Scripts/GameController.cs
> +    }
確かに！

2025-01-03 05:17 UTC, Kenshin0011 commented on Assets/Scripts/ResultManager.cs
> +        Vector2 rightPosition = new Vector2(canvasWidth / 8, canvasHeight / 8);
なぜか今やったら解像度変えても左右対称でできました！
（原因はよくわからないですが…）
```
        Vector2 leftPosition = new Vector2(-canvasWidth / 2, canvasHeight / 8);
        Vector2 rightPosition = new Vector2(canvasWidth / 2, canvasHeight / 8);
```

2025-01-03 05:17 UTC, Kenshin0011 commented
修正しました！
お手隙でご確認お願いします🙇

2025-01-03 06:45 UTC, masayukid reviewed
修正ありがとうございます。
DisplayScore関数のエラー条件を、MaxLampsで書き換えているのもナイスです。
最後に2点だけ、修正をお願いします！

１．Retryしたとき、難易度がNormalになるバグ。
Resultを出すときに、TransitionManager経由で難易度データも渡して、Retry時にはその難易度で再戦できる仕組みにすると良さそうです。（任意）加えて、Result画面に難易度を表示するとさらに良いです。Hardを倒した画面を自慢できるようになります。

２．3点目のゴールを決めた時に、あっさり画面が遷移してしまう点。
勝利判定をGoalPanelの表示より前にしているため、3点目のゴール後ぬるっとResultに遷移しています。案としては、GoalPanelクラスのOpen関数でOnClose時の処理を渡すという方法があるかなと思います。Open(Color color, Action onClose)のようにして、インスタンス変数_onCloseとして保持、Close時に、_onClose()を呼び出して、_onClose=nullとします。こうして、勝利判定をロッドリセット後に移動させ、IsWinnerなら() => EndGame(goalPlayer.IsSelf)を渡し、そうでないならSpawnBallを渡すことで、GoalPanelが表示された後に画面遷移できると思います。他の方法もあると思うので、実装は任せます！

2025-01-03 11:44 UTC, Kenshin0011 commented
修正しました！
（_currentCPUModeをTransition先で毎回定義する処理で良いのか…？）

2025-01-03 13:47 UTC, masayukid approved these changes
ご確認ありがとうございます。
意図通りの実装でした！突き詰めれば他にも良い書き方（LoadSceneMode.Additiveなど）があると思いますが、現段階ではこの書き方で問題ないと思います。

2025-01-03 13:52 UTC, merged